apiVersion: 1
datasources:
  - name: InfluxDB_OPENHAB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://127.0.0.1:8086
    database: openhab2
    basicAuth: true
    basicAuthPassword: true
    basicAuthUser: admin
    basicAuthPassword: admin
    user: openhab
    password: openhab
    isDefault: true
    version: 1
    jsonData:
      timeInterval: ">10s"
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true

  - name: InfluxDB_TELEGRAF
    type: influxdb
    access: proxy
    orgId: 1
    url: http://127.0.0.1:8086
    database: telegraf
    basicAuth: true
    basicAuthPassword: true
    basicAuthUser: admin
    basicAuthPassword: admin
    user: telegraf
    password: telegraf
    isDefault: false
    version: 1
    jsonData:
      timeInterval: ">10s"
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true
