version: "3.8"

services:
  registry:
    image: registry:2
    ports:
    - "5005:5005"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - /data:/var/lib/registry
      - /certs:/certs
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
