version: "3.8"

services:
  registry:
    container_name: local_registry
    image: registry:2
    ports:
    - "5005:5005"
    networks:
      - default
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - /data:/var/lib/registry
      - certificates-vol:/certs
    restart: always
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=public"
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          memory: 20M
      update_config:
        delay: 10s
        order: start-first
        parallelism: 2
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"

networks:
  default:

volumes:
  certificates-vol:
    external: true