version: "3"
services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    networks:
      - monitoring
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_VAR: /rootfs/var
    volumes:
     - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
     - /var:/rootfs/var:ro
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
        - "traefik.tags=private"
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 400M

networks:
  monitoring: