version: "3.8"
services:
  traefik:
    container_name: proxy_traefik
    image: traefik:v2.1
    ports:
      - "80:80"
      - "443:443"
      - "8086:8086"
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.providersThrottleDuration=5s"
      - "--providers.docker.watch=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.swarmModeRefreshSeconds=15s"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`traefik.tags`,`public`)"
      - "--entryPoints.port443.address=:443"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.port8086.address=:8086"
      - "--ping.entryPoint=web"
    deploy:
      placement:
        constraints:
          - node.labels.traefik-public.enable == true
      labels:
        - "traefik.enable=true"
        - "traefik.tags=public"
        - "traefik.http.routers.dashboard.rule=Host(`<domainname>`)"
        - "traefik.http.routers.dashboard.entryPoints=port443"
        - "traefik.http.routers.dashboard.tls=true"
        #- "traefik.http.routers.dashboard.tls.certResolver=le-ssl"
        - "traefik.http.routers.dashboard.service=api@internal"
        
        - "traefik.http.routers.dashboard.middlewares=api-auth"
        - "traefik.http.middlewares.api-auth.basicauth.users=<username>:<hashedpasword

        # global redirect to https
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          memory: 100M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        delay: 10s
        order: start-first
        parallelism: 2
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"

networks:
  traefik-public:
    external: true