version: "3.8"
services:
  influxdb:
    image: localhost:5005/influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      #- influxdb-config:/etc/influxdb/influxdb.conf:ro
      - influxdb-volume:/var/lib/influxdb
      - init.db/init.iql:/docker-entrypoint-initdb.d/
    environment:
      - INFLUXDB_HTTP_HTTPS_ENABLED=false
      #- INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb-selfsigned.crt
      #- INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb-selfsigned.key
      
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true

      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=public"
        - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
        - "traefik.http.routers.influxdb.rule=Host(`deha-it-oh01`)"
        - "traefik.http.routers.influxdb.service=influxdb "
        - "traefik.http.routers.influxdb.entrypoints=port8086"
        #- "traefik.docker.network=traefik"
      replicas: 2
      update_config:
        delay: 10s
        order: start-first
        parallelism: 2
        failure_action: rollback
      rollback_config:
        parallelism: 0
        order: stop-first
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 400M
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "2"

networks:
  monitoring:

volumes:
  #influxdb-config:
  #  external: true
  influxdb-volume:
    external: true


